### PR TITLE
Do not attempt to archive all ivars of PFFile

### PR DESCRIPTION
**Pull request by eladb**
Parse added a few ivars that cannot be archived which broke the category.
Instead, store the URL of the file explicitly.

### CODE REVIEW

**Comment by martinrybak** [comment]
Thank you @eladb! Unfortunately (or fortunately, depending on who you ask :), we are no longer using Parse at our startup. Would you like to take ownership of this repo?

**Comment by eladb** [comment]
Sure, why not

**Comment by eladb** [comment]
How do you want to handover the project? (cocoa pods assignment + github)

**Comment by martinrybak** [comment]
I just transferred the Github repo to you. Not sure what you mean about cocoapods assignment. The old repo URL will be redirected to your new repo URL.

**Comment by eladb** [comment]
I would need a way to publish the pod. I think that should do the trick:

```
pod trunk add-owner Parse-NSCoding elad.benisrael@gmail.com
```

**Comment by martinrybak** [comment]
I haven't claimed ownership yet, so go ahead

**Comment by eladb** [comment]
CoolE.

**Comment by chaitanyapandit** [comment]
Perhaps a better way to validate properties that can be encoded: https://github.com/chaitanyapandit/Parse-NSCoding/commit/b359c20c2dbc198488e5f51db15f9061ed06b053

**Pull request merged**
